theme = "flexoki_dark"

[editor]
color-modes = true
end-of-line-diagnostics = "hint"
line-number = "relative"
rulers = [80]

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.smart-tab]
enable = false

[editor.soft-wrap]
enable = true

[editor.whitespace]
render = "all"

[keys.insert.j]
j = "normal_mode"

[keys.normal]
A-X = "shrink_to_line_bounds"
A-x = "extend_to_line_bounds"
X = "extend_line_above"

[keys.normal.g]
S-l = ["select_mode", "goto_line_end", "normal_mode"]
S-s = ["select_mode", "goto_first_nonwhitespace", "normal_mode"]

